apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:VRiHZ+Nq3zU=,iv:uKCPE9/YaylP6i+IhAmQ9jL/adEU5+L4oLiLicXdOqw=,tag:ffZn2Yr2Pwd3O6SKpgIbAg==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:VBEMEK1hAawirZSs,iv:S546fX4CtWIaiDR1OWI4yDBvqwMl0lTpM8gnjbgM/ZE=,tag:suM5Auu7IIHuqcPVB7oe3Q==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: linkding-container-env
sops:
    age:
        - recipient: age1lqr05j75vh6qxwc5nk0gs5y7h5ra2rssq0e7a737pmvasy33f9zs9l399n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWWUhRaEdCaC9GaHYzc3V0
            WGZGL1dUbzRSMklZV1ArT0lqclBiTjQySWxNCituTnVUc1ZDK3dnZVFPL2tsN0NP
            YWdhc0JNUkZ0UHZHRS9Fb2VhbnlFcE0KLS0tIGtqZTUwVHRISitua2VQRFhMMDd5
            RUlveWdaZ2wyVVp0VmFMTG02allOVFEKjHQ1G7oSCEtPumyUce1b7SFNxh7Nj84B
            5gPTGQ+hELyri0lsqfX1tHqCdFbkwCOvrk3MAJnQJM9EOnCAHSYKbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-05T05:59:48Z"
    mac: ENC[AES256_GCM,data:ZSdzIiQfV273wuHNGoJuaSfoBb6o7BoyL1unqK+wKrkN2NK0pSJpGYUWhmJ81EdCnkE/40rdHiOy8F60P1MJF3/Pe/BI1YVGvSIGg6JNYAnOIH6LVCSelHrCr5x5sfrFkm2SLCKjNKjLKK4TkAY9gxFuTvAATRSkU+AFxqZsNkY=,iv:VIt84f5DULRhteoo9j7MSeIpoj5abalX0GhryxFXi60=,tag:vYgw9AC4+OJt+cevF72eRQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
