apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  settings.yaml: ""
  docker.yaml: ""
  kubernetes.yaml: ""
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/MinhNguyen911
              description: My Github account page
    - Social Media:
        - X:
            - abbr: X
              icon: twitter.svg
              href: https://x.com
        - Reddit:
            - abbr: X
              icon: reddit.svg
              href: https://reddit.com
    - Entertainment:
        - Youtube:
            - abbr: YT
              icon: youtube.svg
              href: https://youtube.com
  services.yaml: |
    - Homelab:
        - Audiobookshelf:
            href: https://audiobookshelf.philipnguyen.uk
            icon: audiobookshelf.svg
            description: Audiobooks and podcasts
        - Linkding:
            href: https://audiobookshelf.philipnguyen.uk
            icon: linkding.svg
            description: Interesting/important bookmarks
        - Grafana:
            href: https://grafana.philipnguyen.uk
            icon: grafana.svg
            description: Monitoring Dashboard

  widgets.yaml: |
    - search:
        provider: [brave, google]
        showSearchSuggestions: true
        target: _blank
    - datetime:
        text_size: xl
        locale: en
        format:
          timeStyle: long
          dateStyle: long
    - resources:
        label: System Resources
        expanded: true
        cpu: true
        memory: true
        uptime: true
        refresh: 1000
        disk:
          - /

