apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  settings.yaml: |
    title: Philip Homepage
    background: 
      image: https://images.pexels.com/photos/531880/pexels-photo-531880.jpeg 
    #  blur:  sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
    #  saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
    #  brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
      opacity: 30 # 0-100
  docker.yaml: ""
  kubernetes.yaml: ""
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/MinhNguyen911
              icon: github.svg
              description: My Github account page
    - Social Media:
        - X:
            - abbr: X
              icon: twitter.svg
              href: https://x.com
        - Reddit:
            - abbr: X
              icon: reddit.svg
              href: https://reddit.com
    - Entertainment:
        - Youtube:
            - abbr: YT
              icon: youtube.svg
              href: https://youtube.com
  services.yaml: |
    - Homelab:
        - Audiobookshelf:
            href: https://audiobookshelf.philipnguyen.uk
            icon: audiobookshelf.svg
            description: Audiobooks and podcasts
        - Linkding:
            href: https://audiobookshelf.philipnguyen.uk
            icon: linkding.svg
            description: Interesting/important bookmarks
        - Grafana:
            href: http://grafana.philipnguyen.uk
            icon: grafana.svg
            description: Monitoring Dashboard

  widgets.yaml: |
    - greeting:
        text_size: 2x1
        text: Welcome to Philip's Server
    - search:
        provider: [brave, google]
        showSearchSuggestions: true
        target: _blank
    - datetime:
        text_size: xl
        locale: en
        format:
          timeStyle: long
          dateStyle: long
    - resources:
        label: System Resources
        expanded: true
        cpu: true
        memory: true
        uptime: true
        refresh: 1000
        disk:
          - /

