apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "66.2.2"
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack
        namespace: monitoring
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
    ignore:
      # Ignore "validated" annotation which is not inserted during install
      - paths: ["/metadata/annotations/prometheus-operator-validated"]
        target:
          kind: PrometheusRule
  values:
    grafana:
      adminPassword: jblunt195
      ingress:
        enabled: true
        path: /
        pathType: Prefix
        hosts:
          - grafana.philipnguyen.uk
        tls:
            hosts:
              - grafana.philipnguyen.uk
      grafana.ini:
        server:
          root_url: https://grafana.philipnguyen.uk
          domain: grafana.philipnguyen.uk
          serve_from_sub_path: false

